// src/api.ts
import axios from 'axios';
import type { ProjectData } from './types/content';

const api = axios.create({
//   baseURL: 'http://localhost:8000/api/', // Update for production
  baseURL: import.meta.env.VITE_API_URL ,
});

// Intercept requests to inject the token
api.interceptors.request.use((config) => {
  const token = sessionStorage.getItem('studio-token');
  if (token) {
    config.headers.Authorization = `Token ${token}`;
  }
  return config;
});

export const fetchProjects = async (): Promise<ProjectData[]> => {
  const response = await api.get('/projects/');
  return response.data;
};

export const createProject = async (data: ProjectData) => {
  const response = await api.post('/projects/', data);
  return response.data;
};

export const updateProject = async (slug: string, data: Partial<ProjectData>) => {
  const response = await api.patch(`/projects/${slug}/`, data);
  return response.data;
};

export const deleteProject = async (slug: string) => {
  await api.delete(`/projects/${slug}/`);
};

// Add this to src/api.ts
export const uploadMedia = async (file: File): Promise<string> => {
  const formData = new FormData();
  formData.append('file', file);

  // We use the api instance so the Auth Token is automatically attached!
  const response = await api.post('/upload/', formData, {
    headers: {
      'Content-Type': 'multipart/form-data',
    },
  });
  
  // Return the S3 URL generated by Django
  return response.data.file; 
};

export default api;